#+TITLE: Lex
#+AUTHOR: lambdart
#+EMAIL: lambdart@protonmail
#+DESCRIPTION: little hacks for vanilla Emacs
#+PROPERTY: header-args :tangle no

Little Hacks for vanilla Emacs.

* Introduction

  A place to put small hacks to be evaluated -
  to improve =Emacs (our lisp machine)= overall usability.

* Overview

  On =Emacs= every user is also a developer, we twist and extend
  the =LISP MACHINE= to meet our needs to become more productive
  by creating new hacks easily.

  This is true for the entire life spam of the user,
  =forever= an =developer=, taking more and more control,
  engaging with the editor's capabilities all day long.

* Version

  - 0.0.5 Alpha

* Dependencies
** Elisp
** Unix
   - mixer
   - scrot
   - slock
   - transset (compton)

* Tested on
  - Emacs 26.3
  - Emacs 28.0.50
  - FreeBSD 12.1

* Install
** Manually
   Clone =lh= repository to a arbitrary location:
   Compile and generate the lh-autoloads.el file.

   #+BEGIN_SRC sh

   [at-lh-root-directory]$ make all

   #+END_SRC

   Add =lh= directory to =load-path= in your
   Emacs initialization file (~init.el~) and load it.

   #+BEGIN_SRC emacs-lisp

   ;; add to load-path
   (add-to-list 'load-path "/full/path/lh/")

   ;; load lh basic features
   (require 'lh-autoloads nil t)

   #+END_SRC

* Customize

  * Note: To see all the options from =Emacs= directly, and to customize it,
    just type: =M-x customize-group RET lh-uu RET=.

* LICENSE
  MIT

* EOF
  All things change in a dynamic environment.
  Your effort to remain what you are is what limits you.
  | Puppet Master |
